/**
 * CATEGORIES and CITIES (with English + Gujarati names), Indian states and GST state codes.
 */
export interface CatalogItem {
  key: string;
  en: string;
  gu: string;
}

export const CATEGORIES = [
  { key: 'business', en: 'Business', gu: 'બિઝનેસ' },
  { key: 'marketing', en: 'Marketing', gu: 'માર્કેટિંગ' },
  { key: 'tech', en: 'Tech', gu: 'ટેક' },
  { key: 'finance', en: 'Finance', gu: 'ફાઇનાન્સ' },
  { key: 'real_estate', en: 'Real Estate', gu: 'રિયલ એસ્ટેટ' },
  { key: 'food', en: 'Food', gu: 'ફૂડ' },
  { key: 'fashion', en: 'Fashion', gu: 'ફેશન' },
  { key: 'beauty', en: 'Beauty', gu: 'બ્યુટી' },
  { key: 'health', en: 'Health', gu: 'હેલ્થ' },
  { key: 'fitness', en: 'Fitness', gu: 'ફિટનેસ' },
  { key: 'travel', en: 'Travel', gu: 'ટ્રાવેલ' },
  { key: 'education', en: 'Education', gu: 'એજ્યુકેશન' },
  { key: 'automobile', en: 'Automobile', gu: 'ઓટોમોબાઇલ' },
  { key: 'home_interior', en: 'Home & Interior', gu: 'હોમ & ઇન્ટિરિયર' },
  { key: 'local_business', en: 'Local Business', gu: 'લોકલ બિઝનેસ' },
  { key: 'entertainment', en: 'Entertainment', gu: 'એન્ટરટેઇનમેન્ટ' },
] as const satisfies readonly CatalogItem[];
export type CategoryKey = (typeof CATEGORIES)[number]['key'];
export const CATEGORY_KEYS = CATEGORIES.map((c) => c.key) as [CategoryKey, ...CategoryKey[]];

/**
 * Cities and towns: every district headquarters of Gujarat (all 34 districts), every municipal corporation and
 * the main towns, A–Z; then "Other (Gujarat)", Mumbai and "Other (India)". Keys are stored in the database: never
 * rename or remove one (add new ones instead). Used for a creator's home city and the areas creators/brands cover.
 */
export const CITIES = [
  { key: 'ahmedabad', en: 'Ahmedabad', gu: 'અમદાવાદ' },
  { key: 'ahwa', en: 'Ahwa (Dang)', gu: 'આહવા (ડાંગ)' },
  { key: 'amreli', en: 'Amreli', gu: 'અમરેલી' },
  { key: 'anand', en: 'Anand', gu: 'આણંદ' },
  { key: 'anjar', en: 'Anjar', gu: 'અંજાર' },
  { key: 'ankleshwar', en: 'Ankleshwar', gu: 'અંકલેશ્વર' },
  { key: 'bagasara', en: 'Bagasara', gu: 'બગસરા' },
  { key: 'bardoli', en: 'Bardoli', gu: 'બારડોલી' },
  { key: 'bavla', en: 'Bavla', gu: 'બાવળા' },
  { key: 'bayad', en: 'Bayad', gu: 'બાયડ' },
  { key: 'bhachau', en: 'Bhachau', gu: 'ભચાઉ' },
  { key: 'bhanvad', en: 'Bhanvad', gu: 'ભાણવડ' },
  { key: 'bharuch', en: 'Bharuch', gu: 'ભરૂચ' },
  { key: 'bhavnagar', en: 'Bhavnagar', gu: 'ભાવનગર' },
  { key: 'bhuj', en: 'Bhuj', gu: 'ભુજ' },
  { key: 'bilimora', en: 'Bilimora', gu: 'બીલીમોરા' },
  { key: 'borsad', en: 'Borsad', gu: 'બોરસદ' },
  { key: 'botad', en: 'Botad', gu: 'બોટાદ' },
  { key: 'chhota_udaipur', en: 'Chhota Udaipur', gu: 'છોટા ઉદેપુર' },
  { key: 'chotila', en: 'Chotila', gu: 'ચોટીલા' },
  { key: 'dabhoi', en: 'Dabhoi', gu: 'ડભોઈ' },
  { key: 'dahod', en: 'Dahod', gu: 'દાહોદ' },
  { key: 'dakor', en: 'Dakor', gu: 'ડાકોર' },
  { key: 'deesa', en: 'Deesa', gu: 'ડીસા' },
  { key: 'dehgam', en: 'Dehgam', gu: 'દહેગામ' },
  { key: 'devgadh_baria', en: 'Devgadh Baria', gu: 'દેવગઢ બારિયા' },
  { key: 'dhandhuka', en: 'Dhandhuka', gu: 'ધંધુકા' },
  { key: 'dhanera', en: 'Dhanera', gu: 'ધાનેરા' },
  { key: 'dharampur', en: 'Dharampur', gu: 'ધરમપુર' },
  { key: 'dholka', en: 'Dholka', gu: 'ધોળકા' },
  { key: 'dhoraji', en: 'Dhoraji', gu: 'ધોરાજી' },
  { key: 'dhrangadhra', en: 'Dhrangadhra', gu: 'ધ્રાંગધ્રા' },
  { key: 'dhrol', en: 'Dhrol', gu: 'ધ્રોલ' },
  { key: 'dwarka', en: 'Dwarka', gu: 'દ્વારકા' },
  { key: 'gadhada', en: 'Gadhada', gu: 'ગઢડા' },
  { key: 'gandevi', en: 'Gandevi', gu: 'ગણદેવી' },
  { key: 'gandhidham', en: 'Gandhidham', gu: 'ગાંધીધામ' },
  { key: 'gandhinagar', en: 'Gandhinagar', gu: 'ગાંધીનગર' },
  { key: 'godhra', en: 'Godhra', gu: 'ગોધરા' },
  { key: 'gondal', en: 'Gondal', gu: 'ગોંડલ' },
  { key: 'halol', en: 'Halol', gu: 'હાલોલ' },
  { key: 'halvad', en: 'Halvad', gu: 'હળવદ' },
  { key: 'himmatnagar', en: 'Himmatnagar', gu: 'હિંમતનગર' },
  { key: 'idar', en: 'Idar', gu: 'ઈડર' },
  { key: 'jambusar', en: 'Jambusar', gu: 'જંબુસર' },
  { key: 'jamjodhpur', en: 'Jamjodhpur', gu: 'જામજોધપુર' },
  { key: 'jamnagar', en: 'Jamnagar', gu: 'જામનગર' },
  { key: 'jasdan', en: 'Jasdan', gu: 'જસદણ' },
  { key: 'jetpur', en: 'Jetpur', gu: 'જેતપુર' },
  { key: 'jhalod', en: 'Jhalod', gu: 'ઝાલોદ' },
  { key: 'junagadh', en: 'Junagadh', gu: 'જૂનાગઢ' },
  { key: 'kadi', en: 'Kadi', gu: 'કડી' },
  { key: 'kalavad', en: 'Kalavad', gu: 'કાલાવડ' },
  { key: 'kalol_gandhinagar', en: 'Kalol (Gandhinagar)', gu: 'કલોલ (ગાંધીનગર)' },
  { key: 'kalol_panchmahal', en: 'Kalol (Panchmahal)', gu: 'કાલોલ (પંચમહાલ)' },
  { key: 'kapadvanj', en: 'Kapadvanj', gu: 'કપડવંજ' },
  { key: 'karjan', en: 'Karjan', gu: 'કરજણ' },
  { key: 'keshod', en: 'Keshod', gu: 'કેશોદ' },
  { key: 'khambhalia', en: 'Khambhalia', gu: 'ખંભાળિયા' },
  { key: 'khambhat', en: 'Khambhat', gu: 'ખંભાત' },
  { key: 'khedbrahma', en: 'Khedbrahma', gu: 'ખેડબ્રહ્મા' },
  { key: 'kodinar', en: 'Kodinar', gu: 'કોડીનાર' },
  { key: 'kutiyana', en: 'Kutiyana', gu: 'કુતિયાણા' },
  { key: 'lathi', en: 'Lathi', gu: 'લાઠી' },
  { key: 'limbdi', en: 'Limbdi', gu: 'લીંબડી' },
  { key: 'lunawada', en: 'Lunawada', gu: 'લુણાવાડા' },
  { key: 'mahuva', en: 'Mahuva', gu: 'મહુવા' },
  { key: 'manavadar', en: 'Manavadar', gu: 'માણાવદર' },
  { key: 'mandvi_kutch', en: 'Mandvi (Kutch)', gu: 'માંડવી (કચ્છ)' },
  { key: 'mandvi_surat', en: 'Mandvi (Surat)', gu: 'માંડવી (સુરત)' },
  { key: 'mangrol', en: 'Mangrol', gu: 'માંગરોળ' },
  { key: 'mansa', en: 'Mansa', gu: 'માણસા' },
  { key: 'mehsana', en: 'Mehsana', gu: 'મહેસાણા' },
  { key: 'modasa', en: 'Modasa', gu: 'મોડાસા' },
  { key: 'morbi', en: 'Morbi', gu: 'મોરબી' },
  { key: 'mundra', en: 'Mundra', gu: 'મુંદ્રા' },
  { key: 'nadiad', en: 'Nadiad', gu: 'નડિયાદ' },
  { key: 'navsari', en: 'Navsari', gu: 'નવસારી' },
  { key: 'okha', en: 'Okha', gu: 'ઓખા' },
  { key: 'padra', en: 'Padra', gu: 'પાદરા' },
  { key: 'palanpur', en: 'Palanpur', gu: 'પાલનપુર' },
  { key: 'palitana', en: 'Palitana', gu: 'પાલીતાણા' },
  { key: 'pardi', en: 'Pardi', gu: 'પારડી' },
  { key: 'patan', en: 'Patan', gu: 'પાટણ' },
  { key: 'petlad', en: 'Petlad', gu: 'પેટલાદ' },
  { key: 'porbandar', en: 'Porbandar', gu: 'પોરબંદર' },
  { key: 'prantij', en: 'Prantij', gu: 'પ્રાંતિજ' },
  { key: 'rajkot', en: 'Rajkot', gu: 'રાજકોટ' },
  { key: 'rajpipla', en: 'Rajpipla', gu: 'રાજપીપળા' },
  { key: 'rajula', en: 'Rajula', gu: 'રાજુલા' },
  { key: 'ranavav', en: 'Ranavav', gu: 'રાણાવાવ' },
  { key: 'rapar', en: 'Rapar', gu: 'રાપર' },
  { key: 'salaya', en: 'Salaya', gu: 'સલાયા' },
  { key: 'sanand', en: 'Sanand', gu: 'સાણંદ' },
  { key: 'santrampur', en: 'Santrampur', gu: 'સંતરામપુર' },
  { key: 'savarkundla', en: 'Savarkundla', gu: 'સાવરકુંડલા' },
  { key: 'savli', en: 'Savli', gu: 'સાવલી' },
  { key: 'siddhpur', en: 'Siddhpur', gu: 'સિદ્ધપુર' },
  { key: 'sihor', en: 'Sihor', gu: 'સિહોર' },
  { key: 'songadh', en: 'Songadh', gu: 'સોનગઢ' },
  { key: 'surat', en: 'Surat', gu: 'સુરત' },
  { key: 'surendranagar', en: 'Surendranagar', gu: 'સુરેન્દ્રનગર' },
  { key: 'talaja', en: 'Talaja', gu: 'તળાજા' },
  { key: 'thangadh', en: 'Thangadh', gu: 'થાનગઢ' },
  { key: 'tharad', en: 'Tharad', gu: 'થરાદ' },
  { key: 'umbergaon', en: 'Umbergaon', gu: 'ઉમરગામ' },
  { key: 'umreth', en: 'Umreth', gu: 'ઉમરેઠ' },
  { key: 'una', en: 'Una', gu: 'ઉના' },
  { key: 'unjha', en: 'Unjha', gu: 'ઊંઝા' },
  { key: 'upleta', en: 'Upleta', gu: 'ઉપલેટા' },
  { key: 'vadnagar', en: 'Vadnagar', gu: 'વડનગર' },
  { key: 'vadodara', en: 'Vadodara', gu: 'વડોદરા' },
  { key: 'valsad', en: 'Valsad', gu: 'વલસાડ' },
  { key: 'vanthali', en: 'Vanthali', gu: 'વંથલી' },
  { key: 'vapi', en: 'Vapi', gu: 'વાપી' },
  { key: 'veraval', en: 'Veraval', gu: 'વેરાવળ' },
  { key: 'viramgam', en: 'Viramgam', gu: 'વિરમગામ' },
  { key: 'visavadar', en: 'Visavadar', gu: 'વિસાવદર' },
  { key: 'visnagar', en: 'Visnagar', gu: 'વિસનગર' },
  { key: 'vyara', en: 'Vyara', gu: 'વ્યારા' },
  { key: 'wadhwan', en: 'Wadhwan', gu: 'વઢવાણ' },
  { key: 'wankaner', en: 'Wankaner', gu: 'વાંકાનેર' },
  { key: 'other_gujarat', en: 'Other (Gujarat)', gu: 'અન્ય (ગુજરાત)' },
  { key: 'mumbai', en: 'Mumbai', gu: 'મુંબઈ' },
  { key: 'other_india', en: 'Other (India)', gu: 'અન્ય (ભારત)' },
] as const satisfies readonly CatalogItem[];
export type CityKey = (typeof CITIES)[number]['key'];
export const CITY_KEYS = CITIES.map((c) => c.key) as [CityKey, ...CityKey[]];

/** GST state codes. Bluenova is registered in Gujarat (24). */
export const INDIAN_STATES = [
  { code: '01', name: 'Jammu & Kashmir' }, { code: '02', name: 'Himachal Pradesh' },
  { code: '03', name: 'Punjab' }, { code: '04', name: 'Chandigarh' },
  { code: '05', name: 'Uttarakhand' }, { code: '06', name: 'Haryana' },
  { code: '07', name: 'Delhi' }, { code: '08', name: 'Rajasthan' },
  { code: '09', name: 'Uttar Pradesh' }, { code: '10', name: 'Bihar' },
  { code: '11', name: 'Sikkim' }, { code: '12', name: 'Arunachal Pradesh' },
  { code: '13', name: 'Nagaland' }, { code: '14', name: 'Manipur' },
  { code: '15', name: 'Mizoram' }, { code: '16', name: 'Tripura' },
  { code: '17', name: 'Meghalaya' }, { code: '18', name: 'Assam' },
  { code: '19', name: 'West Bengal' }, { code: '20', name: 'Jharkhand' },
  { code: '21', name: 'Odisha' }, { code: '22', name: 'Chhattisgarh' },
  { code: '23', name: 'Madhya Pradesh' }, { code: '24', name: 'Gujarat' },
  { code: '26', name: 'Dadra & Nagar Haveli and Daman & Diu' }, { code: '27', name: 'Maharashtra' },
  { code: '29', name: 'Karnataka' }, { code: '30', name: 'Goa' },
  { code: '31', name: 'Lakshadweep' }, { code: '32', name: 'Kerala' },
  { code: '33', name: 'Tamil Nadu' }, { code: '34', name: 'Puducherry' },
  { code: '35', name: 'Andaman & Nicobar Islands' }, { code: '36', name: 'Telangana' },
  { code: '37', name: 'Andhra Pradesh' }, { code: '38', name: 'Ladakh' },
] as const;
export const STATE_CODES = INDIAN_STATES.map((s) => s.code) as [string, ...string[]];
export const BLUENOVA_STATE_CODE = '24';

export function catalogLabel(list: readonly CatalogItem[], key: string, lang: 'gu' | 'en'): string {
  const item = list.find((i) => i.key === key);
  return item ? item[lang] : key;
}
